/**
 * The per-launch debug overlay: a loopback MCP endpoint plus the cordis patch
 * file that mounts it inside a managed Runtime.
 *
 * The patch is written once per launch and deleted with it, which does more than
 * keep the folder tidy: a distinct path changes the composition hash, so no peer
 * window adopts a Runtime that carries another window's debug endpoint.
 */
import { randomUUID } from "node:crypto";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type * as vscode from "vscode";
import type { DebugContextTracker } from "./debugContext";
import { startDebugMcpServer, type DebugMcpServerHandle } from "./debugMcpServer";
import { createDebugToolHost, type DebugToolHost } from "./debugToolHandlers";

/** The patch file reads the bearer token from here, so the secret never lands on disk. */
export const DEBUG_TOKEN_ENV = "DSH_IDE_DEBUG_TOKEN";

const PATCH_PREFIX = "debug-";
const PATCH_SUFFIX = ".patch.yml";
const MCP_PATH = "/mcp";
const MCP_SERVER_NAME = "dsh-debug";
/** Namespaces the model-facing names as `mcp__debug__<tool>`; Harness requires [A-Za-z0-9_-]{1,32}. */
const MCP_NAMESPACE = "debug";
const MCP_SERVER_VERSION = "1.0.0";

export interface DebugLaunchOptions {
    /** Directory that already holds extension-owned launch files. */
    directory: string;
    /** This launch's owner id, used to name the patch file. */
    ownerId: string;
    tracker: DebugContextTracker;
    maxContextBytes?: number;
    log: (message: string) => void;
}

export class DebugLaunchOverlay implements vscode.Disposable {
    private constructor(
        private readonly server: DebugMcpServerHandle,
        private readonly tools: DebugToolHost,
        public readonly patchPath: string,
    ) {}

    /** Brings the endpoint up first: the patch file needs its URL. */
    public static async create(options: DebugLaunchOptions): Promise<DebugLaunchOverlay> {
        const tools = createDebugToolHost({
            tracker: options.tracker,
            log: options.log,
            ...(options.maxContextBytes === undefined ? {} : { maxContextBytes: options.maxContextBytes }),
        });
        let server: DebugMcpServerHandle | undefined;
        try {
            server = await startDebugMcpServer({
                token: randomUUID(),
                tools: tools.tools,
                execute: (name, args) => tools.execute(name, args),
                path: MCP_PATH,
                serverName: MCP_SERVER_NAME,
                serverVersion: MCP_SERVER_VERSION,
                log: options.log,
            });
            const patchPath = join(
                options.directory,
                `${PATCH_PREFIX}${process.pid}-${options.ownerId}${PATCH_SUFFIX}`,
            );
            await mkdir(options.directory, { recursive: true });
            await writeFile(patchPath, patchBody(server.url), { encoding: "utf8", mode: 0o600 });
            await sweepStalePatches(options.directory, patchPath, options.log);
            return new DebugLaunchOverlay(server, tools, patchPath);
        } catch (error) {
            tools.dispose();
            await server?.stop();
            throw error;
        }
    }

    /** Environment the launched Runtime needs to answer its own bearer challenge. */
    public get environment(): Record<string, string> {
        return { [DEBUG_TOKEN_ENV]: this.server.token };
    }

    public dispose(): Promise<void> {
        this.tools.dispose();
        return this.server.stop().finally(() => rm(this.patchPath, { force: true }));
    }
}

function patchBody(url: string): string {
    // A --patch overlay is a loader *patch* list, so the plugin must be inserted:
    // a bare entry would target an existing id and warn-and-skip when absent.
    return `# Generated by dsh-ide for one Runtime launch. Turn off dsh.autonomousDebugging to stop writing it.
- insert:
    - id: dsh-ide-debug
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: ${MCP_NAMESPACE}
        transport: streamable-http
        url: ${url}
        headers:
          # Quoted: a plain YAML scalar cannot start with the backtick this template needs.
          Authorization: !!js '\`Bearer \${process.env.${DEBUG_TOKEN_ENV}}\`'
        # An unavailable debugger must never stop the Runtime from booting.
        failOnStartupError: false
`;
}

/**
 * A window killed before its cleanup can only leave behind a URL and an
 * environment variable name, but the folder should not fill up over time.
 */
async function sweepStalePatches(
    directory: string,
    keep: string,
    log: (message: string) => void,
): Promise<void> {
    const entries = await readdir(directory).catch(() => [] as string[]);
    for (const entry of entries) {
        if (!entry.startsWith(PATCH_PREFIX) || !entry.endsWith(PATCH_SUFFIX)) continue;
        const path = join(directory, entry);
        if (path === keep) continue;
        const pid = Number(/^debug-(\d+)-/u.exec(entry)?.[1]);
        if (!Number.isInteger(pid) || pid <= 0 || isProcessAlive(pid)) continue;
        await rm(path, { force: true }).catch(() => undefined);
        log(`removed stale debug patch left by process ${pid}: ${entry}`);
    }
}

function isProcessAlive(pid: number): boolean {
    try {
        process.kill(pid, 0);
        return true;
    } catch (error) {
        return (error as NodeJS.ErrnoException).code === "EPERM";
    }
}
