/**
 * A loopback Streamable HTTP MCP server, so the managed runtime can drive the
 * IDE debugger without the extension owning a plugin in the composition.
 *
 * Hand-rolled on purpose: the MCP SDK pulls ~90 packages into a build that
 * otherwise ships one runtime dependency, and the protocol surface the
 * `@deepseek-ai/dsh-mcp-client` bridge exercises is small — `initialize`,
 * `tools/list`, `tools/call`. A stateless JSON server is legal for that
 * client: no `MCP-Session-Id` is required, and `405` on GET is the documented
 * answer for "this server has no SSE stream".
 */
import { timingSafeEqual } from "node:crypto";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { AddressInfo } from "node:net";
import type { DebugToolInfo, DebugToolOutcome } from "./debugToolHandlers";

const SUPPORTED_PROTOCOL_VERSIONS = ["2025-11-25", "2025-06-18", "2025-03-26", "2024-11-05", "2024-10-07"];
const LATEST_PROTOCOL_VERSION = SUPPORTED_PROTOCOL_VERSIONS[0];
const MAX_BODY_BYTES = 256 * 1024;
const TOKEN_MIN_LENGTH = 32;

const PARSE_ERROR = -32700;
const INVALID_REQUEST = -32600;
const METHOD_NOT_FOUND = -32601;
const INVALID_PARAMS = -32602;
const INTERNAL_ERROR = -32603;

type JsonRecord = { [key: string]: unknown };

export interface DebugMcpServerOptions {
    /** Bearer secret the runtime must present; generated by the caller per launch. */
    token: string;
    tools: readonly DebugToolInfo[];
    execute(name: string, args: unknown): Promise<DebugToolOutcome>;
    serverName?: string;
    serverVersion?: string;
    host?: string;
    port?: number;
    path?: string;
    log?: (message: string) => void;
}

export interface DebugMcpServerHandle {
    readonly url: string;
    readonly token: string;
    stop(): Promise<void>;
}

interface RpcMessage {
    id: string | number | null;
    method: string;
    params: JsonRecord;
    isNotification: boolean;
}

/** Binds the server; rejects if the token is too weak or the port cannot be taken. */
export async function startDebugMcpServer(options: DebugMcpServerOptions): Promise<DebugMcpServerHandle> {
    const token = options.token;
    if (token.length < TOKEN_MIN_LENGTH) {
        throw new Error(`debug MCP token must be at least ${TOKEN_MIN_LENGTH} characters`);
    }
    const host = options.host ?? "127.0.0.1";
    const endpointPath = normalizePath(options.path ?? "/mcp");
    const serverName = options.serverName ?? "dsh-debug";
    const serverVersion = options.serverVersion ?? "0.0.0";
    const log = options.log ?? (() => undefined);
    const toolByName = new Map(options.tools.map((tool) => [tool.name, tool]));

    const handler = (request: IncomingMessage, response: ServerResponse) => {
        void route({
            request,
            response,
            token,
            endpointPath,
            host: () => allowedHosts(host, boundPort),
            serverName,
            serverVersion,
            toolByName,
            options,
            log,
        });
    };
    const server = createServer(handler);
    server.on("clientError", (error) => log(`rejected MCP client connection: ${error.message}`));

    await new Promise<void>((resolve, reject) => {
        const onError = (error: Error) => reject(error);
        server.once("error", onError);
        server.listen(options.port ?? 0, host, () => {
            server.removeListener("error", onError);
            resolve();
        });
    });
    const address = server.address() as AddressInfo | string | null;
    const boundPort = typeof address === "object" && address ? address.port : (options.port ?? 0);
    const url = `http://${host}:${boundPort}${endpointPath}`;
    log(`listening on ${url}`);

    let stopping: Promise<void> | undefined;
    const stop = (): Promise<void> => {
        stopping = stopping ?? new Promise<void>((resolve) => {
            server.close(() => resolve());
            server.closeAllConnections?.();
        });
        return stopping;
    };
    return { url, token, stop };
}

async function route(context: {
    request: IncomingMessage;
    response: ServerResponse;
    token: string;
    endpointPath: string;
    host: () => Set<string>;
    serverName: string;
    serverVersion: string;
    toolByName: Map<string, DebugToolInfo>;
    options: DebugMcpServerOptions;
    log: (message: string) => void;
}): Promise<void> {
    const { request, response } = context;
    const method = request.method ?? "GET";
    if (method !== "POST") {
        // 405 on GET is the spec's "no SSE stream here", which the client accepts.
        respond(response, 405, { allowed: "POST" });
        return;
    }
    if (requestUrl(request) !== context.endpointPath) {
        respond(response, 404, { payload: rpcError(null, INVALID_REQUEST, "not found") });
        return;
    }
    if (!authorize(request, context.token)) {
        respond(response, 401, {
            wwwAuthenticate: `Bearer realm="${context.serverName}"`,
            payload: rpcError(null, INVALID_REQUEST, "missing or invalid bearer token"),
        });
        return;
    }
    const hostHeader = request.headers.host;
    if (!hostHeader || !context.host().has(hostHeader.toLowerCase())) {
        context.log(`rejected request with Host: ${hostHeader ?? "(none)"}`);
        respond(response, 403, { payload: rpcError(null, INVALID_REQUEST, "Host header does not match the loopback endpoint") });
        return;
    }
    const protocolHeader = request.headers["mcp-protocol-version"];
    if (typeof protocolHeader === "string" && protocolHeader.length > 0
        && !SUPPORTED_PROTOCOL_VERSIONS.includes(protocolHeader)) {
        respond(response, 400, { payload: rpcError(null, INVALID_REQUEST, `unsupported MCP-Protocol-Version ${protocolHeader}`) });
        return;
    }
    const contentType = request.headers["content-type"];
    if (typeof contentType === "string" && !contentType.toLowerCase().includes("application/json")) {
        respond(response, 415, { payload: rpcError(null, INVALID_REQUEST, "content-type must be application/json") });
        return;
    }
    const accept = request.headers.accept;
    if (typeof accept === "string" && accept.length > 0
        && !accept.includes("application/json") && !accept.includes("*/*")) {
        respond(response, 406, { payload: rpcError(null, INVALID_REQUEST, "this endpoint serves application/json only") });
        return;
    }
    const declaredLength = Number(request.headers["content-length"]);
    if (Number.isFinite(declaredLength) && declaredLength > MAX_BODY_BYTES) {
        respond(response, 413, { payload: rpcError(null, INVALID_REQUEST, `request body exceeds ${MAX_BODY_BYTES} bytes`) });
        return;
    }

    let body: string;
    try {
        body = await readBody(request);
    } catch (error) {
        context.log(`body read failed: ${errorMessage(error)}`);
        respond(response, 400, { payload: rpcError(null, PARSE_ERROR, "could not read request body") });
        return;
    }

    let parsed: unknown;
    try {
        parsed = JSON.parse(body);
    } catch {
        respond(response, 400, { payload: rpcError(null, PARSE_ERROR, "request body is not valid JSON") });
        return;
    }
    if (Array.isArray(parsed)) {
        // JSON-RPC batching was removed from the 2025-03-26 revision of the protocol.
        respond(response, 400, { payload: rpcError(null, INVALID_REQUEST, "batched requests are not supported") });
        return;
    }
    const message = toRpcMessage(parsed);
    if (!message) {
        respond(response, 400, { payload: rpcError(null, INVALID_REQUEST, "expected a JSON-RPC request object") });
        return;
    }
    if (message.isNotification) {
        response.writeHead(202, { "content-type": "application/json", "cache-control": "no-store" });
        response.end();
        return;
    }

    try {
        const result = await handleRequest(message, context);
        if (result.error) {
            respond(response, 200, { payload: rpcError(message.id, result.error.code, result.error.message) });
            return;
        }
        respond(response, 200, { payload: { jsonrpc: "2.0", id: message.id, result: result.value } });
    } catch (error) {
        context.log(`request ${message.method} failed: ${errorMessage(error)}`);
        respond(response, 200, { payload: rpcError(message.id, INTERNAL_ERROR, "internal error") });
    }
}

interface HandleResult {
    value?: JsonRecord;
    error?: { code: number; message: string };
}

async function handleRequest(
    message: RpcMessage,
    context: {
        serverName: string;
        serverVersion: string;
        toolByName: Map<string, DebugToolInfo>;
        options: DebugMcpServerOptions;
        log: (message: string) => void;
    },
): Promise<HandleResult> {
    switch (message.method) {
        case "initialize": {
            const requested = typeof message.params.protocolVersion === "string" ? message.params.protocolVersion : undefined;
            const protocolVersion = requested && SUPPORTED_PROTOCOL_VERSIONS.includes(requested)
                ? requested
                : LATEST_PROTOCOL_VERSION;
            return {
                value: {
                    protocolVersion,
                    capabilities: { tools: { listChanged: false } },
                    serverInfo: { name: context.serverName, version: context.serverVersion },
                    instructions: "These tools drive the debugger in the IDE the agent is paired with. Start a launch configuration the user already has, set breakpoints, then wait for a pause and read debug_context.",
                },
            };
        }
        case "ping":
            return { value: {} };
        case "tools/list":
            return { value: { tools: context.options.tools } };
        case "tools/call": {
            const name = typeof message.params.name === "string" ? message.params.name : undefined;
            if (!name) return { error: { code: INVALID_PARAMS, message: "name is required" } };
            const tool = context.toolByName.get(name);
            if (!tool) return { error: { code: INVALID_PARAMS, message: `unknown tool "${name}"` } };
            const argsValue = message.params.arguments;
            if (argsValue !== undefined && (typeof argsValue !== "object" || argsValue === null || Array.isArray(argsValue))) {
                return { error: { code: INVALID_PARAMS, message: "arguments must be an object" } };
            }
            context.log(`call ${name}`);
            let outcome: DebugToolOutcome;
            try {
                outcome = await context.options.execute(name, argsValue ?? {});
            } catch (error) {
                outcome = { text: `${name} failed: ${errorMessage(error)}`, isError: true };
            }
            return {
                value: {
                    content: [{ type: "text", text: outcome.text }],
                    isError: outcome.isError,
                },
            };
        }
        default:
            return { error: { code: METHOD_NOT_FOUND, message: `method ${message.method} is not supported` } };
    }
}

function readBody(request: IncomingMessage): Promise<string> {
    return new Promise<string>((resolve, reject) => {
        const chunks: Buffer[] = [];
        let size = 0;
        request.on("data", (chunk: Buffer) => {
            size += chunk.length;
            if (size > MAX_BODY_BYTES) {
                reject(new Error("request body too large"));
                request.destroy();
                return;
            }
            chunks.push(chunk);
        });
        request.on("error", reject);
        request.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    });
}

function toRpcMessage(value: unknown): RpcMessage | undefined {
    if (typeof value !== "object" || value === null || Array.isArray(value)) return undefined;
    const record = value as JsonRecord;
    if (record.jsonrpc !== "2.0" || typeof record.method !== "string") return undefined;
    const id = record.id;
    const hasId = (typeof id === "string" || typeof id === "number" || id === null);
    return {
        method: record.method,
        params: typeof record.params === "object" && record.params !== null && !Array.isArray(record.params)
            ? record.params as JsonRecord
            : {},
        id: hasId ? (id as string | number | null) : null,
        isNotification: !hasId || record.method.startsWith("notifications/"),
    };
}

function authorize(request: IncomingMessage, token: string): boolean {
    const header = request.headers.authorization;
    if (typeof header !== "string" || !header.toLowerCase().startsWith("bearer ")) return false;
    return secretsMatch(header.slice(7).trim(), token);
}

function secretsMatch(presented: string, expected: string): boolean {
    const left = Buffer.from(presented, "utf8");
    const right = Buffer.from(expected, "utf8");
    if (left.length !== right.length) return false;
    return timingSafeEqual(left, right);
}

function allowedHosts(host: string, port: number): Set<string> {
    const targets = new Set([`${host}:${port}`, `localhost:${port}`, `127.0.0.1:${port}`, `[::1]:${port}`]);
    if (host.startsWith("[")) targets.add(host);
    return targets;
}

function requestUrl(request: IncomingMessage): string {
    const raw = request.url ?? "/";
    const index = raw.indexOf("?");
    return index === -1 ? raw : raw.slice(0, index);
}

function normalizePath(value: string): string {
    const trimmed = value.startsWith("/") ? value : `/${value}`;
    return trimmed.length > 1 && trimmed.endsWith("/") ? trimmed.slice(0, -1) : trimmed;
}

function respond(
    response: ServerResponse,
    status: number,
    init: { payload?: unknown; allowed?: string; wwwAuthenticate?: string } = {},
): void {
    const headers: Record<string, string> = {
        "content-type": "application/json",
        "cache-control": "no-store",
    };
    if (init.allowed) headers.allow = init.allowed;
    if (init.wwwAuthenticate) headers["www-authenticate"] = init.wwwAuthenticate;
    const body = init.payload === undefined ? "" : JSON.stringify(init.payload);
    if (body) headers["content-length"] = String(Buffer.byteLength(body, "utf8"));
    response.writeHead(status, headers);
    response.end(body);
}

function rpcError(id: string | number | null, code: number, message: string): JsonRecord {
    return {
        jsonrpc: "2.0",
        id,
        error: { code, message },
    };
}

function errorMessage(error: unknown): string {
    return error instanceof Error ? error.message : String(error);
}
